


-- 멤버 테이블 생성
DROP TABLE AR_MEMBER ;

CREATE TABLE AR_MEMBER(
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(30) NOT NULL,
	MEMBER_PW VARCHAR2(30) NOT NULL,
	MEMBER_NAME VARCHAR(30),
	SECESSION CHAR(2) DEFAULT 'N'
);

SELECT * FROM AR_MEMBER;


-- MEMBER_NO 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO;



-- 어항 정보 테이블 생성
DROP TABLE AR_TANK;

CREATE TABLE AR_TANK(
	MEMBER_NO NUMBER REFERENCES AR_MEMBER,
	TANK_NO NUMBER,
	TANK_NAME VARCHAR2(30),
	FRESH_SALT CHAR(2) DEFAULT 'S',
	TANK_SIZE VARCHAR2(50),
	TANK_LIGHT VARCHAR2(100),
	TANK_FILTER VARCHAR2(100),
	TANK_ADDICTIVE VARCHAR2(100),
	TANK_SUBSTRATE VARCHAR2(50),
	CONSTRAINT PK_MEMBER_TANK PRIMARY KEY(MEMBER_NO, TANK_NO));

COMMIT;

SELECT * FROM AR_TANK;

SELECT TANK_NO, TANK_NAME
		FROM AR_TANK
		WHERE MEMBER_NO = 1;
	
INSERT INTO AR_TANK 
VALUES(1, 1, '내어항1', DEFAULT, '45큐브', 'K7 PRO', '하단섬프', '제오박, CV', '산호사');


SELECT * FROM TANK_INFO;

-- 로그인
SELECT MEMBER_NO, MEMBER_ID, MEMBER_NAME
FROM AR_MEMBER
WHERE MEMBER_ID = ''
AND MEMBER_PW = '';



-- 회원 가입
INSERT INTO AR_MEMBER 
VALUES(SEQ_MEMBER_NO.NEXTVAL, ?, ?, ?, DEFAULT);

INSERT INTO AR_MEMBER 
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user01', 'pass01', '유저일', DEFAULT);













