
--1. 
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS 주소지
FROM TB_STUDENT ts
ORDER BY 1;

--2. 
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT ts 
WHERE ABSENCE_YN = 'Y'
ORDER BY 2 DESC;

--3. 
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS 거주지
FROM TB_STUDENT ts 
WHERE STUDENT_ADDRESS LIKE('%경기도%') 
AND STUDENT_NO LIKE('9%')
ORDER BY 1;

--4.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR tp 
WHERE DEPARTMENT_NO = '005'
ORDER BY PROFESSOR_SSN;


--5.
SELECT STUDENT_NO, TO_CHAR(POINT, 'FM9.00') 학점
FROM TB_GRADE
WHERE CLASS_NO = 'C3118100' AND TERM_NO = '200402'
ORDER BY 2 DESC, 1 ;


--6.
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT ts 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY 2;


--7.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_DEPARTMENT td 
JOIN TB_CLASS USING(DEPARTMENT_NO);


--8.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS_PROFESSOR tcp 
JOIN TB_PROFESSOR USING(PROFESSOR_NO)
JOIN TB_CLASS USING(CLASS_NO);


--9.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_PROFESSOR P
JOIN TB_CLASS_PROFESSOR USING(PROFESSOR_NO)
JOIN TB_CLASS USING(CLASS_NO)
JOIN TB_DEPARTMENT D ON(P.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE CATEGORY = '인문사회';


--10.
SELECT STUDENT_NO 학번, STUDENT_NAME "학생 이름", ROUND(AVG(POINT),1) "전체 평점"
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NO = '059'
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY 1;


--11.
SELECT DEPARTMENT_NAME 학과이름, STUDENT_NAME 학생이름, PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';


--12.
SELECT STUDENT_NAME, TERM_NO TERM_NAME
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE CLASS_NO = 'C2604100' AND TERM_NO LIKE('2007%')


--13.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
FULL JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '예체능' AND PROFESSOR_NO IS NULL;


--14.
SELECT STUDENT_NAME 학생이름, NVL(PROFESSOR_NAME, '지도교수 미지정') 지도교수
FROM TB_STUDENT SD
LEFT JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE SD.DEPARTMENT_NO = '020'
ORDER BY STUDENT_NO ;


--15.
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, DEPARTMENT_NAME "학과 이름", AVG(POINT) 평점
FROM TB_STUDENT ST
JOIN TB_DEPARTMENT td USING(DEPARTMENT_NO)
JOIN TB_GRADE tg USING(STUDENT_NO)
WHERE ST.ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(POINT) >= 4.0
ORDER BY 1;


--16.
SELECT CLASS_NO, CLASS_NAME, TRUNC(AVG(POINT),8)
FROM TB_GRADE tg 
JOIN TB_CLASS tc USING(CLASS_NO)
WHERE DEPARTMENT_NO = '034' AND CLASS_TYPE LIKE('%전공%')
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY 1;


--17.
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_STUDENT ts WHERE STUDENT_NAME = '최경희');


--18.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NO = '001'
GROUP BY STUDENT_NO, STUDENT_NAME
HAVING AVG(POINT) = (SELECT MAX(AVG(POINT)) 
					FROM TB_GRADE 
					JOIN TB_STUDENT USING(STUDENT_NO) 
					WHERE DEPARTMENT_NO = '001' 
					GROUP BY STUDENT_NO)

			
					
SELECT STUDENT_NO , STUDENT_NAME 
FROM (
SELECT STUDENT_NO, STUDENT_NAME, AVG(POINT) 평점
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY 평점 DESC)
WHERE ROWNUM = 1;



SELECT STUDENT_NO , STUDENT_NAME 
FROM (
SELECT STUDENT_NO, STUDENT_NAME, AVG(POINT) 평점
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_DEPARTMENT
						WHERE DEPARTMENT_NAME = '국어국문학과')
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY 평점 DESC)
WHERE ROWNUM = 1;



-- 19.
SELECT DEPARTMENT_NAME "계열 학과명", ROUND(AVG(POINT),1) 전공평점
FROM TB_DEPARTMENT
JOIN TB_CLASS USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(CLASS_NO)
WHERE CATEGORY = (SELECT CATEGORY 
					FROM TB_DEPARTMENT
					WHERE DEPARTMENT_NAME = '환경조경학과')
AND CLASS_TYPE LIKE('전공%')
GROUP BY DEPARTMENT_NAME
ORDER BY 1;

					